"""Conversations: context construction, replies, persistence.

Two classes with different lifetimes, and the split matters.

:class:`ConversationService` runs inside a request's unit of work and handles
everything that completes before a response starts.

:class:`ChatStreamer` owns its own sessions, because a streaming response's
body is produced *after* the endpoint returns -- by which point FastAPI has
already closed the request-scoped session. Using it there would fail on the
first write, and holding one open for the length of a stream would pin a pool
connection to however long the model takes to think.
"""

from __future__ import annotations

import time
import uuid
from collections.abc import AsyncGenerator
from contextlib import aclosing
from dataclasses import dataclass, field

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from nova.ai.base import ChatMessage, ChatProvider, ChatRequest, EmbeddingProvider
from nova.ai.errors import AIProviderError
from nova.core.clock import utc_now
from nova.core.config import AISettings
from nova.core.errors import NotFoundError
from nova.core.logging import get_logger
from nova.models.conversation import Conversation, Message
from nova.repositories.conversation import ConversationRepository, MessageRepository
from nova.repositories.memory import MemoryRepository
from nova.schemas.conversation import (
    ConversationDetail,
    ConversationRead,
    MessageExchange,
    MessageRead,
)
from nova.services.memory import MemoryService
from nova.services.persona import Persona, build_system_prompt

logger = get_logger(__name__)

# Messages returned by conversation detail; the newest ones.
CONVERSATION_DETAIL_MESSAGE_LIMIT = 200

# A title is derived from the opening message rather than asked for or
# generated by a second model call -- a companion should not interrogate you
# about naming a chat.
TITLE_MAX_LENGTH = 60


@dataclass(frozen=True, slots=True)
class PreparedTurn:
    """Everything settled before a streaming reply starts.

    Grouped rather than returned as a tuple because the third element --
    retrieved memory -- is easy to drop silently when unpacking, and dropping
    it means NOVA quietly stops remembering anything.
    """

    user_message: MessageRead
    history: list[ChatMessage] = field(default_factory=list)
    context: str | None = None


class ConversationService:
    """Request-scoped conversation operations."""

    def __init__(
        self,
        *,
        conversations: ConversationRepository,
        messages: MessageRepository,
        provider: ChatProvider,
        settings: AISettings,
        persona: Persona | None = None,
        memories: MemoryService | None = None,
    ) -> None:
        self._conversations = conversations
        self._messages = messages
        self._provider = provider
        self._settings = settings
        self._persona = persona or Persona()
        # Optional so the conversation path still works with memory turned
        # off, which is what the retrieval-free tests exercise.
        self._memories = memories

    # -- reading ----------------------------------------------------------

    async def list_conversations(self, owner_id: uuid.UUID) -> list[ConversationRead]:
        return [
            ConversationRead.model_validate(conversation)
            for conversation in await self._conversations.list_for_owner(owner_id)
        ]

    async def get_conversation(
        self, conversation_id: uuid.UUID, owner_id: uuid.UUID
    ) -> ConversationDetail:
        conversation = await self.require_owned(conversation_id, owner_id)
        # The newest page only. A thread that has been open for months is
        # thousands of rows, and loading all of them to show the bottom of
        # the screen is the request that gets slower every day. The total is
        # still in ``message_count``, so a client can tell it was cut.
        messages = await self._messages.list_recent(
            conversation.id, limit=CONVERSATION_DETAIL_MESSAGE_LIMIT
        )

        return ConversationDetail(
            **ConversationRead.model_validate(conversation).model_dump(),
            messages=[MessageRead.model_validate(m) for m in messages],
        )

    # -- writing ----------------------------------------------------------

    async def create_conversation(
        self, owner_id: uuid.UUID, *, title: str | None = None
    ) -> ConversationRead:
        conversation = Conversation(user_id=owner_id, title=title)
        self._conversations.add(conversation)
        await self._conversations.session.flush()

        logger.info("conversation_created", conversation_id=str(conversation.id))
        return ConversationRead.model_validate(conversation)

    async def delete_conversation(self, conversation_id: uuid.UUID, owner_id: uuid.UUID) -> None:
        conversation = await self.require_owned(conversation_id, owner_id)
        await self._conversations.delete(conversation)
        logger.info("conversation_deleted", conversation_id=str(conversation_id))

    async def send_message(
        self, conversation_id: uuid.UUID, owner_id: uuid.UUID, content: str
    ) -> MessageExchange:
        """Send a message and wait for the whole reply.

        The non-streaming path. Clients that show tokens as they arrive use
        :class:`ChatStreamer` instead; this exists for callers with nobody
        watching, and because a synchronous path is far easier to test.
        """
        conversation = await self.require_owned(conversation_id, owner_id)

        user_message = self.append_message(conversation, role="user", content=content)
        await self._conversations.session.flush()

        history = await self.recent_history(conversation.id)
        context = await self.memory_context(owner_id, content)

        started = time.perf_counter()
        completion = await self._provider.complete(
            ChatRequest(
                system=build_system_prompt(self._persona),
                messages=history,
                context=context,
                max_tokens=self._settings.max_reply_tokens,
            )
        )
        latency_ms = int((time.perf_counter() - started) * 1000)

        assistant_message = self.append_message(
            conversation,
            role="assistant",
            content=completion.text,
            provider=self._provider.name,
            model=completion.model,
            input_tokens=completion.usage.input_tokens,
            output_tokens=completion.usage.output_tokens,
            latency_ms=latency_ms,
        )
        await self._conversations.session.flush()

        logger.info(
            "message_exchanged",
            conversation_id=str(conversation.id),
            provider=self._provider.name,
            latency_ms=latency_ms,
        )
        return MessageExchange(
            user_message=MessageRead.model_validate(user_message),
            assistant_message=MessageRead.model_validate(assistant_message),
        )

    # -- shared with ChatStreamer -----------------------------------------

    async def require_owned(self, conversation_id: uuid.UUID, owner_id: uuid.UUID) -> Conversation:
        conversation = await self._conversations.get_for_owner(conversation_id, owner_id)
        if conversation is None:
            raise NotFoundError("Conversation not found.", code="conversation_not_found")
        return conversation

    async def recent_history(self, conversation_id: uuid.UUID) -> list[ChatMessage]:
        """The recent turns, in reading order.

        Bounded so cost does not grow without limit as a thread ages. Older
        context comes back through semantic memory in Phase 5 rather than by
        raising this ceiling.
        """
        recent = await self._messages.list_recent(
            conversation_id, limit=self._settings.context_window_messages
        )
        return [
            ChatMessage(role=m.role, content=m.content)  # type: ignore[arg-type]
            for m in recent
        ]

    async def memory_context(self, owner_id: uuid.UUID, query: str) -> str | None:
        """What NOVA remembers that bears on ``query``.

        Failure here is not failure of the reply: an unreachable embedder
        should cost continuity, not the answer. So this degrades to no
        memories rather than propagating.
        """
        if self._memories is None:
            return None

        try:
            return await self._memories.context_for(owner_id, query)
        except Exception:
            logger.exception("memory_retrieval_failed", user_id=str(owner_id))
            return None

    def append_message(
        self,
        conversation: Conversation,
        *,
        role: str,
        content: str,
        **fields: object,
    ) -> Message:
        message = Message(conversation_id=conversation.id, role=role, content=content, **fields)
        self._messages.add(message)

        conversation.message_count += 1
        conversation.last_message_at = utc_now()
        if conversation.title is None and role == "user":
            conversation.title = derive_title(content)

        return message


class ChatStreamer:
    """Streams a reply, owning its own database sessions.

    Three phases, each with its own short transaction:

    1. verify ownership, persist the user turn, read back the context;
    2. stream from the provider with no session held open;
    3. persist the assistant turn.

    Phase 3 runs even when the client disconnects mid-stream. A half-received
    reply is still something NOVA said, and losing it would leave the thread
    showing a question with no answer.
    """

    def __init__(
        self,
        *,
        session_factory: async_sessionmaker[AsyncSession],
        provider: ChatProvider,
        settings: AISettings,
        persona: Persona | None = None,
        embeddings: EmbeddingProvider | None = None,
    ) -> None:
        self._session_factory = session_factory
        self._provider = provider
        self._settings = settings
        self._persona = persona or Persona()
        self._embeddings = embeddings

    async def prepare(
        self, conversation_id: uuid.UUID, owner_id: uuid.UUID, content: str
    ) -> PreparedTurn:
        """Persist the user's turn and gather everything the reply needs.

        Runs before the response starts, so an unknown conversation or an
        invalid payload still produces a normal error response rather than
        an error event inside a stream the client has begun rendering.

        Retrieval happens here too, in the same transaction: it reads and
        writes (recall counts), and doing it mid-stream would mean opening a
        second session while the first is still committing.
        """
        async with self._session_factory() as session:
            service = self._service(session)
            conversation = await service.require_owned(conversation_id, owner_id)
            user_message = service.append_message(conversation, role="user", content=content)
            await session.flush()
            history = await service.recent_history(conversation.id)
            context = await service.memory_context(owner_id, content)
            stored = MessageRead.model_validate(user_message)
            await session.commit()

        return PreparedTurn(user_message=stored, history=history, context=context)

    async def stream(
        self,
        conversation_id: uuid.UUID,
        history: list[ChatMessage],
        context: str | None = None,
    ) -> AsyncGenerator[str, None]:
        """Yield reply text, persisting whatever was produced.

        Raises:
            AIProviderError: if the provider fails before any text arrives.
                Once text has been yielded the response is already streaming,
                so a later failure ends the stream and keeps the partial
                reply rather than raising into a body already in flight.
        """
        chunks: list[str] = []
        started = time.perf_counter()
        failed: AIProviderError | None = None

        try:
            # ``aclosing``: closing this generator must close the provider's
            # stream in the same step. ``async for`` on its own would leave
            # the provider suspended for the garbage collector -- and for the
            # Anthropic provider that is an open HTTP stream.
            async with aclosing(
                self._provider.stream(
                    ChatRequest(
                        system=build_system_prompt(self._persona),
                        messages=history,
                        context=context,
                        max_tokens=self._settings.max_reply_tokens,
                    )
                )
            ) as provider_chunks:
                async for chunk in provider_chunks:
                    chunks.append(chunk)
                    yield chunk
        except AIProviderError as exc:
            failed = exc
            if not chunks:
                # Nothing was sent yet, so this can still surface properly.
                raise
            logger.warning(
                "ai_stream_failed_midway",
                conversation_id=str(conversation_id),
                chars=sum(len(c) for c in chunks),
                error=exc.code,
            )
        finally:
            # Also runs when the client disconnects, which cancels the
            # generator: whatever NOVA managed to say is still recorded.
            if chunks:
                await self._persist_reply(
                    conversation_id,
                    text="".join(chunks),
                    latency_ms=int((time.perf_counter() - started) * 1000),
                    truncated=failed is not None,
                )

    async def _persist_reply(
        self, conversation_id: uuid.UUID, *, text: str, latency_ms: int, truncated: bool
    ) -> None:
        async with self._session_factory() as session:
            conversation = await session.get(Conversation, conversation_id)
            if conversation is None:  # pragma: no cover - deleted mid-stream
                return

            MessageRepository(session).add(
                Message(
                    conversation_id=conversation_id,
                    role="assistant",
                    content=text,
                    provider=self._provider.name,
                    model=self._provider.model,
                    latency_ms=latency_ms,
                )
            )
            conversation.message_count += 1
            conversation.last_message_at = utc_now()
            await session.commit()

        logger.info(
            "reply_persisted",
            conversation_id=str(conversation_id),
            latency_ms=latency_ms,
            truncated=truncated,
        )

    def _service(self, session: AsyncSession) -> ConversationService:
        memories = (
            MemoryService(
                memories=MemoryRepository(session),
                embeddings=self._embeddings,
                settings=self._settings,
            )
            if self._embeddings is not None
            else None
        )
        return ConversationService(
            conversations=ConversationRepository(session),
            messages=MessageRepository(session),
            provider=self._provider,
            settings=self._settings,
            persona=self._persona,
            memories=memories,
        )


def derive_title(content: str) -> str:
    """Make a conversation title from its opening message.

    Cut on a word boundary so a truncated title does not end mid-word.
    """
    flattened = " ".join(content.split())
    if len(flattened) <= TITLE_MAX_LENGTH:
        return flattened

    clipped = flattened[:TITLE_MAX_LENGTH]
    if " " in clipped:
        clipped = clipped[: clipped.rfind(" ")]
    return f"{clipped}…"
