"""Conversations: context construction, tool use, replies, persistence.

Two classes with different lifetimes, and the split matters.

:class:`ConversationService` runs inside a request's unit of work and handles
everything that completes before a response starts.

:class:`ChatStreamer` owns its own sessions, because a streaming response's
body is produced *after* the endpoint returns -- by which point FastAPI has
already closed the request-scoped session. Using it there would fail on the
first write, and holding one open for the length of a stream would pin a pool
connection to however long the model takes to think.

The streamer also runs the tool loop. That loop is bounded by
``ToolSettings.max_tool_rounds`` and nothing else: there is no condition under
which NOVA keeps calling tools until it decides it is finished. An agent that
runs until satisfied is explicitly out of scope, and a bound that is a
configured number rather than a heuristic is a bound you can reason about.
"""

from __future__ import annotations

import time
import uuid
from collections.abc import AsyncGenerator
from contextlib import aclosing
from dataclasses import dataclass, field

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from nova.ai.base import (
    ChatMessage,
    ChatProvider,
    ChatRequest,
    EmbeddingProvider,
    StreamCompleted,
    StreamEvent,
    TextDelta,
    ToolCall,
    ToolCallRequested,
    ToolOutcome,
)
from nova.ai.errors import AIProviderError
from nova.core.clock import utc_now
from nova.core.config import AISettings, ToolSettings
from nova.core.errors import NotFoundError
from nova.core.logging import get_logger
from nova.models.conversation import Conversation, Message
from nova.repositories.conversation import ConversationRepository, MessageRepository
from nova.repositories.memory import MemoryRepository
from nova.schemas.conversation import (
    ConversationDetail,
    ConversationRead,
    MessageExchange,
    MessageRead,
)
from nova.services.memory import MemoryService
from nova.services.persona import Persona, build_system_prompt
from nova.services.tools import ToolService, tool_context
from nova.tools.base import ToolContext
from nova.tools.errors import ToolError

logger = get_logger(__name__)

# A title is derived from the opening message rather than asked for or
# generated by a second model call -- nobody wants to be interrogated about
# naming a chat.
TITLE_MAX_LENGTH = 60


@dataclass(frozen=True, slots=True)
class PreparedTurn:
    """Everything settled before a streaming reply starts.

    Grouped rather than returned as a tuple because the third element --
    retrieved memory -- is easy to drop silently when unpacking, and dropping
    it means NOVA quietly stops remembering anything.
    """

    user_message: MessageRead
    history: list[ChatMessage] = field(default_factory=list)
    context: str | None = None


# -- what a streamed reply emits ----------------------------------------------


@dataclass(frozen=True, slots=True)
class ReplyDelta:
    """A fragment of visible text."""

    text: str


@dataclass(frozen=True, slots=True)
class ToolStarted:
    """NOVA has begun running a tool."""

    call_id: str
    name: str


@dataclass(frozen=True, slots=True)
class ToolFinished:
    """A tool has returned."""

    call_id: str
    name: str
    summary: str
    is_error: bool
    duration_ms: int


@dataclass(frozen=True, slots=True)
class ConfirmationNeeded:
    """NOVA wants to do something that needs a person's approval.

    Carries the token the client presents to go ahead, so the app can render
    a prompt with a working button rather than telling someone to go and find
    the tools screen.
    """

    call_id: str
    name: str
    prompt: str
    confirmation_token: str
    arguments: dict[str, object]
    expires_in_seconds: int


ReplyEvent = ReplyDelta | ToolStarted | ToolFinished | ConfirmationNeeded


class ConversationService:
    """Request-scoped conversation operations."""

    def __init__(
        self,
        *,
        conversations: ConversationRepository,
        messages: MessageRepository,
        provider: ChatProvider,
        settings: AISettings,
        persona: Persona | None = None,
        memories: MemoryService | None = None,
    ) -> None:
        self._conversations = conversations
        self._messages = messages
        self._provider = provider
        self._settings = settings
        self._persona = persona or Persona()
        # Optional so the conversation path still works with memory turned
        # off, which is what the retrieval-free tests exercise.
        self._memories = memories

    # -- reading ----------------------------------------------------------

    async def list_conversations(self, owner_id: uuid.UUID) -> list[ConversationRead]:
        return [
            ConversationRead.model_validate(conversation)
            for conversation in await self._conversations.list_for_owner(owner_id)
        ]

    async def get_conversation(
        self, conversation_id: uuid.UUID, owner_id: uuid.UUID
    ) -> ConversationDetail:
        conversation = await self.require_owned(conversation_id, owner_id)
        messages = await self._messages.list_for_conversation(conversation.id)

        return ConversationDetail(
            **ConversationRead.model_validate(conversation).model_dump(),
            messages=[MessageRead.model_validate(m) for m in messages],
        )

    # -- writing ----------------------------------------------------------

    async def create_conversation(
        self, owner_id: uuid.UUID, *, title: str | None = None
    ) -> ConversationRead:
        conversation = Conversation(user_id=owner_id, title=title)
        self._conversations.add(conversation)
        await self._conversations.session.flush()

        logger.info("conversation_created", conversation_id=str(conversation.id))
        return ConversationRead.model_validate(conversation)

    async def delete_conversation(self, conversation_id: uuid.UUID, owner_id: uuid.UUID) -> None:
        conversation = await self.require_owned(conversation_id, owner_id)
        await self._conversations.delete(conversation)
        logger.info("conversation_deleted", conversation_id=str(conversation_id))

    async def send_message(
        self, conversation_id: uuid.UUID, owner_id: uuid.UUID, content: str
    ) -> MessageExchange:
        """Send a message and wait for the whole reply.

        The non-streaming path, and deliberately the *tool-free* one. Tool use
        is something a person watches happen; running it with nobody looking
        means an action they did not see proposed. Clients that want tools use
        :class:`ChatStreamer`.
        """
        conversation = await self.require_owned(conversation_id, owner_id)

        user_message = self.append_message(conversation, role="user", content=content)
        await self._conversations.session.flush()

        history = await self.recent_history(conversation.id)
        context = await self.memory_context(owner_id, content)

        started = time.perf_counter()
        completion = await self._provider.complete(
            ChatRequest(
                system=build_system_prompt(self._persona, has_tools=False),
                messages=history,
                context=context,
                max_tokens=self._settings.max_reply_tokens,
            )
        )
        latency_ms = int((time.perf_counter() - started) * 1000)

        assistant_message = self.append_message(
            conversation,
            role="assistant",
            content=completion.text,
            provider=self._provider.name,
            model=completion.model,
            input_tokens=completion.usage.input_tokens,
            output_tokens=completion.usage.output_tokens,
            latency_ms=latency_ms,
        )
        await self._conversations.session.flush()

        logger.info(
            "message_exchanged",
            conversation_id=str(conversation.id),
            provider=self._provider.name,
            latency_ms=latency_ms,
        )
        return MessageExchange(
            user_message=MessageRead.model_validate(user_message),
            assistant_message=MessageRead.model_validate(assistant_message),
        )

    # -- shared with ChatStreamer -----------------------------------------

    async def require_owned(self, conversation_id: uuid.UUID, owner_id: uuid.UUID) -> Conversation:
        conversation = await self._conversations.get_for_owner(conversation_id, owner_id)
        if conversation is None:
            raise NotFoundError("Conversation not found.", code="conversation_not_found")
        return conversation

    async def recent_history(self, conversation_id: uuid.UUID) -> list[ChatMessage]:
        """The recent turns, in reading order.

        Bounded so cost does not grow without limit as a thread ages. Older
        context comes back through semantic memory rather than by raising
        this ceiling.
        """
        recent = await self._messages.list_recent(
            conversation_id, limit=self._settings.context_window_messages
        )
        return [
            ChatMessage(role=m.role, content=m.content)  # type: ignore[arg-type]
            for m in recent
        ]

    async def memory_context(self, owner_id: uuid.UUID, query: str) -> str | None:
        """What NOVA remembers that bears on ``query``.

        Failure here is not failure of the reply: an unreachable embedder
        should cost continuity, not the answer. So this degrades to no
        memories rather than propagating.
        """
        if self._memories is None:
            return None

        try:
            return await self._memories.context_for(owner_id, query)
        except Exception:
            logger.exception("memory_retrieval_failed", user_id=str(owner_id))
            return None

    def append_message(
        self,
        conversation: Conversation,
        *,
        role: str,
        content: str,
        **fields: object,
    ) -> Message:
        message = Message(conversation_id=conversation.id, role=role, content=content, **fields)
        self._messages.add(message)

        conversation.message_count += 1
        conversation.last_message_at = utc_now()
        if conversation.title is None and role == "user":
            conversation.title = derive_title(content)

        return message


class ChatStreamer:
    """Streams a reply, running tools along the way and owning its sessions.

    Three phases, each with its own short transaction:

    1. verify ownership, persist the user turn, read back the context;
    2. stream from the provider -- possibly several times, with tool results
       in between -- holding no session open across a model call;
    3. persist the assistant turn.

    Phase 3 runs even when the client disconnects mid-stream. A half-received
    reply is still something NOVA said, and losing it would leave the thread
    showing a question with no answer.
    """

    def __init__(
        self,
        *,
        session_factory: async_sessionmaker[AsyncSession],
        provider: ChatProvider,
        settings: AISettings,
        persona: Persona | None = None,
        embeddings: EmbeddingProvider | None = None,
        tools: ToolService | None = None,
        tool_settings: ToolSettings | None = None,
    ) -> None:
        self._session_factory = session_factory
        self._provider = provider
        self._settings = settings
        self._persona = persona or Persona()
        self._embeddings = embeddings
        self._tools = tools
        self._tool_settings = tool_settings or ToolSettings()

    @property
    def _tools_available(self) -> bool:
        """Whether this reply can use tools at all.

        Three things have to line up: a tool service, a provider that can
        choose a tool, and a round budget above zero. A provider that cannot
        is not given definitions -- see
        :func:`~nova.services.persona.build_system_prompt`.
        """
        return (
            self._tools is not None
            and self._provider.supports_tools
            and self._tool_settings.max_tool_rounds > 0
        )

    async def prepare(
        self, conversation_id: uuid.UUID, owner_id: uuid.UUID, content: str
    ) -> PreparedTurn:
        """Persist the user's turn and gather everything the reply needs.

        Runs before the response starts, so an unknown conversation or an
        invalid payload still produces a normal error response rather than
        an error event inside a stream the client has begun rendering.

        Retrieval happens here too, in the same transaction: it reads and
        writes (recall counts), and doing it mid-stream would mean opening a
        second session while the first is still committing.
        """
        async with self._session_factory() as session:
            service = self._service(session)
            conversation = await service.require_owned(conversation_id, owner_id)
            user_message = service.append_message(conversation, role="user", content=content)
            await session.flush()
            history = await service.recent_history(conversation.id)
            context = await service.memory_context(owner_id, content)
            stored = MessageRead.model_validate(user_message)
            await session.commit()

        return PreparedTurn(user_message=stored, history=history, context=context)

    async def stream(
        self,
        conversation_id: uuid.UUID,
        owner_id: uuid.UUID,
        history: list[ChatMessage],
        context: str | None = None,
        *,
        request_id: str | None = None,
    ) -> AsyncGenerator[ReplyEvent, None]:
        """Yield reply events, persisting whatever text was produced.

        Raises:
            AIProviderError: if the provider fails before any text arrives.
                Once text has been yielded the response is already streaming,
                so a later failure ends the stream and keeps the partial
                reply rather than raising into a body already in flight.
        """
        # Everything NOVA says across every round; this is what gets stored
        # as the assistant's message.
        spoken: list[str] = []
        started = time.perf_counter()
        failed: AIProviderError | None = None
        turns = list(history)

        try:
            for round_index in range(self._tool_settings.max_tool_rounds + 1):
                # The last round is answered without tools, so the model has
                # to produce a reply rather than asking for one more thing.
                last_round = round_index == self._tool_settings.max_tool_rounds
                calls: list[ToolCall] = []
                # Only this round's text. Kept separate from ``spoken``
                # because the assistant turn appended below describes *this*
                # request; reusing the running total would replay every
                # earlier round's words back into the next prompt.
                said_now: list[str] = []

                async with aclosing(
                    self._model_turn(turns, context, offer_tools=not last_round)
                ) as events:
                    async for event in events:
                        match event:
                            case TextDelta(text=text):
                                said_now.append(text)
                                spoken.append(text)
                                yield ReplyDelta(text)
                            case ToolCallRequested(call=call):
                                calls.append(call)
                            case StreamCompleted():
                                pass

                if not calls:
                    return

                if last_round:
                    # A tool asked for in a round where none were offered.
                    # A provider given no definitions should not be able to
                    # produce this, so it is either a confused model or a
                    # provider that ignored the request -- and NOVA does not
                    # run a tool it did not offer. Without this the bound
                    # would be "max_tool_rounds, unless the model insists",
                    # which is not a bound.
                    logger.warning(
                        "tool_call_after_budget",
                        conversation_id=str(conversation_id),
                        tools=[call.name for call in calls],
                    )
                    return

                # The assistant's own turn has to be in the history before its
                # results are, or the next request describes results answering
                # a request that was never made -- which every provider
                # rejects, and rightly.
                turns.append(
                    ChatMessage(
                        role="assistant",
                        content="".join(said_now),
                        tool_calls=tuple(calls),
                    )
                )
                outcomes: list[ToolOutcome] = []

                for call in calls:
                    # A different name from the provider events above: these
                    # are NOVA's own events, and reusing the binding would let
                    # the two vocabularies be confused for each other.
                    async for reply_event in self._run_call(
                        call, owner_id, conversation_id, request_id, outcomes
                    ):
                        yield reply_event

                turns.append(ChatMessage(role="user", tool_results=tuple(outcomes)))
        except AIProviderError as exc:
            failed = exc
            if not spoken:
                # Nothing was sent yet, so this can still surface properly.
                raise
            logger.warning(
                "ai_stream_failed_midway",
                conversation_id=str(conversation_id),
                chars=sum(len(c) for c in spoken),
                error=exc.code,
            )
        finally:
            # Also runs when the client disconnects, which cancels the
            # generator: whatever NOVA managed to say is still recorded.
            if spoken:
                await self._persist_reply(
                    conversation_id,
                    text="".join(spoken),
                    latency_ms=int((time.perf_counter() - started) * 1000),
                    truncated=failed is not None,
                )

    def _model_turn(
        self, turns: list[ChatMessage], context: str | None, *, offer_tools: bool
    ) -> AsyncGenerator[StreamEvent, None]:
        """One request to the provider.

        ``aclosing``: closing this must close the provider's stream in the
        same step. ``async for`` alone would leave the provider suspended for
        the garbage collector -- and for an HTTP provider that is an open
        connection.
        """
        definitions = (
            self._tools.definitions_for_model()
            if offer_tools and self._tools is not None and self._tools_available
            else ()
        )
        return self._provider.stream(
            ChatRequest(
                system=build_system_prompt(self._persona, has_tools=self._tools_available),
                messages=turns,
                context=context,
                max_tokens=self._settings.max_reply_tokens,
                tools=definitions,
            )
        )

    async def _run_call(
        self,
        call: ToolCall,
        owner_id: uuid.UUID,
        conversation_id: uuid.UUID,
        request_id: str | None,
        outcomes: list[ToolOutcome],
    ) -> AsyncGenerator[ReplyEvent, None]:
        """Run one tool the model asked for, emitting what the app should show.

        Every failure mode ends with something appended to ``outcomes``. A
        model left without a result for a call it made will either hang or
        invent one, and both are worse than being told plainly that the tool
        refused.
        """
        if self._tools is None:  # pragma: no cover - guarded by _tools_available
            return

        yield ToolStarted(call_id=call.id, name=call.name)
        started = time.perf_counter()

        context = tool_context(
            user_id=owner_id,
            request_id=request_id,
            conversation_id=conversation_id,
            initiated_by_model=True,
        )

        try:
            invocation = await self._tools.invoke(call.name, call.arguments, context)
        except ToolError as exc:
            duration_ms = int((time.perf_counter() - started) * 1000)

            # A destructive tool is not run; it is offered. The person gets a
            # prompt with a token, and the model is told to wait rather than
            # being left to guess what happened.
            if exc.code == "tool_needs_confirmation":
                async for event in self._propose(call, context, outcomes):
                    yield event
                return

            outcomes.append(
                ToolOutcome(
                    call_id=call.id,
                    name=call.name,
                    content=f"{exc.message} (refused: {exc.code})",
                    is_error=True,
                )
            )
            yield ToolFinished(
                call_id=call.id,
                name=call.name,
                summary=exc.message,
                is_error=True,
                duration_ms=duration_ms,
            )
            return

        outcomes.append(
            ToolOutcome(
                call_id=call.id,
                name=call.name,
                content=invocation.result.content,
                is_error=invocation.result.is_error,
            )
        )
        yield ToolFinished(
            call_id=call.id,
            name=call.name,
            summary=_summarise(invocation.result.content),
            is_error=invocation.result.is_error,
            duration_ms=invocation.duration_ms,
        )

    async def _propose(
        self, call: ToolCall, context: ToolContext, outcomes: list[ToolOutcome]
    ) -> AsyncGenerator[ReplyEvent, None]:
        """Turn a refused destructive call into something the person can approve."""
        if self._tools is None:  # pragma: no cover - guarded by the caller
            return

        try:
            pending = await self._tools.propose(call.name, call.arguments, context)
        except ToolError as exc:
            outcomes.append(
                ToolOutcome(
                    call_id=call.id,
                    name=call.name,
                    content=f"{exc.message} (refused: {exc.code})",
                    is_error=True,
                )
            )
            yield ToolFinished(
                call_id=call.id,
                name=call.name,
                summary=exc.message,
                is_error=True,
                duration_ms=0,
            )
            return

        outcomes.append(
            ToolOutcome(
                call_id=call.id,
                name=call.name,
                content=(
                    "Not run. This action changes things, so it is waiting for the "
                    "person to approve it. Tell them what it would do and stop; do "
                    "not try again and do not describe it as done."
                ),
                is_error=False,
            )
        )
        yield ConfirmationNeeded(
            call_id=call.id,
            name=call.name,
            prompt=pending.prompt,
            confirmation_token=pending.token,
            arguments=dict(pending.arguments),
            expires_in_seconds=pending.expires_in_seconds,
        )

    async def _persist_reply(
        self, conversation_id: uuid.UUID, *, text: str, latency_ms: int, truncated: bool
    ) -> None:
        async with self._session_factory() as session:
            conversation = await session.get(Conversation, conversation_id)
            if conversation is None:  # pragma: no cover - deleted mid-stream
                return

            MessageRepository(session).add(
                Message(
                    conversation_id=conversation_id,
                    role="assistant",
                    content=text,
                    provider=self._provider.name,
                    model=self._provider.model,
                    latency_ms=latency_ms,
                )
            )
            conversation.message_count += 1
            conversation.last_message_at = utc_now()
            await session.commit()

        logger.info(
            "reply_persisted",
            conversation_id=str(conversation_id),
            latency_ms=latency_ms,
            truncated=truncated,
        )

    def _service(self, session: AsyncSession) -> ConversationService:
        memories = (
            MemoryService(
                memories=MemoryRepository(session),
                embeddings=self._embeddings,
                settings=self._settings,
            )
            if self._embeddings is not None
            else None
        )
        return ConversationService(
            conversations=ConversationRepository(session),
            messages=MessageRepository(session),
            provider=self._provider,
            settings=self._settings,
            persona=self._persona,
            memories=memories,
        )


def _summarise(content: str) -> str:
    """The first line of a tool result, for the chip the app shows.

    The full result is in the audit log and in what the model was given; the
    UI needs something that fits on one line under a spinner.
    """
    first = content.strip().split("\n", 1)[0]
    return first if len(first) <= 120 else f"{first[:117]}…"


def derive_title(content: str) -> str:
    """Make a conversation title from its opening message.

    Cut on a word boundary so a truncated title does not end mid-word.
    """
    flattened = " ".join(content.split())
    if len(flattened) <= TITLE_MAX_LENGTH:
        return flattened

    clipped = flattened[:TITLE_MAX_LENGTH]
    if " " in clipped:
        clipped = clipped[: clipped.rfind(" ")]
    return f"{clipped}…"
