"""device platform: devices, credentials, claims, telemetry

Revision ID: 978f18a302cf
Revises: de83c7e06397
Create Date: 2026-09-06 15:16:01.214372+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "978f18a302cf"
down_revision: str | None = "de83c7e06397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("hardware_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("firmware_version", sa.String(length=32), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_devices_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(op.f("ix_devices_hardware_id"), "devices", ["hardware_id"], unique=True)
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "device_claims",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("provisioning_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_claims_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_claims")),
    )
    op.create_index(op.f("ix_device_claims_code_hash"), "device_claims", ["code_hash"], unique=True)
    op.create_index(
        op.f("ix_device_claims_device_id"), "device_claims", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_device_claims_provisioning_token_hash"),
        "device_claims",
        ["provisioning_token_hash"],
        unique=True,
    )
    op.create_table(
        "device_credentials",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_credentials_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_credentials")),
    )
    op.create_index(
        op.f("ix_device_credentials_device_id"), "device_credentials", ["device_id"], unique=False
    )
    op.create_index(
        "ix_device_credentials_device_id_active",
        "device_credentials",
        ["device_id"],
        unique=False,
        postgresql_where="revoked_at IS NULL",
    )
    op.create_index(
        op.f("ix_device_credentials_token_hash"), "device_credentials", ["token_hash"], unique=True
    )
    op.create_table(
        "device_telemetry",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("battery_percent", sa.Integer(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("distance_cm", sa.Integer(), nullable=True),
        sa.Column("head_yaw", sa.Integer(), nullable=True),
        sa.Column("head_pitch", sa.Integer(), nullable=True),
        sa.Column("wifi_rssi", sa.Integer(), nullable=True),
        sa.Column("uptime_seconds", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "battery_percent IS NULL OR (battery_percent BETWEEN 0 AND 100)",
            name=op.f("ck_device_telemetry_battery_percent_range"),
        ),
        sa.CheckConstraint(
            "distance_cm IS NULL OR distance_cm >= 0",
            name=op.f("ck_device_telemetry_distance_non_negative"),
        ),
        sa.CheckConstraint(
            "uptime_seconds IS NULL OR uptime_seconds >= 0",
            name=op.f("ck_device_telemetry_uptime_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_telemetry_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_telemetry")),
    )
    op.create_index(
        op.f("ix_device_telemetry_device_id"), "device_telemetry", ["device_id"], unique=False
    )
    op.create_index(
        "ix_device_telemetry_device_id_recorded_at",
        "device_telemetry",
        ["device_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_telemetry_event_type"), "device_telemetry", ["event_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_telemetry_event_type"), table_name="device_telemetry")
    op.drop_index("ix_device_telemetry_device_id_recorded_at", table_name="device_telemetry")
    op.drop_index(op.f("ix_device_telemetry_device_id"), table_name="device_telemetry")
    op.drop_table("device_telemetry")
    op.drop_index(op.f("ix_device_credentials_token_hash"), table_name="device_credentials")
    op.drop_index(
        "ix_device_credentials_device_id_active",
        table_name="device_credentials",
        postgresql_where="revoked_at IS NULL",
    )
    op.drop_index(op.f("ix_device_credentials_device_id"), table_name="device_credentials")
    op.drop_table("device_credentials")
    op.drop_index(op.f("ix_device_claims_provisioning_token_hash"), table_name="device_claims")
    op.drop_index(op.f("ix_device_claims_device_id"), table_name="device_claims")
    op.drop_index(op.f("ix_device_claims_code_hash"), table_name="device_claims")
    op.drop_table("device_claims")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_hardware_id"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
