"""user timezone

Revision ID: d5949ac01523
Revises: 6ba65af67f31
Create Date: 2026-09-06 17:00:37.049047+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d5949ac01523"
down_revision: str | None = "6ba65af67f31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL with a server default, so existing rows are backfilled by the
    # ALTER itself. Adding it nullable and tightening later would need a
    # second migration and leave a window where analytics had to cope with a
    # null timezone.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###
