"""semantic memory

Revision ID: 6ba65af67f31
Revises: ab3cf85a302c
Create Date: 2026-09-06 16:20:03.381552+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "6ba65af67f31"
down_revision: str | None = "ab3cf85a302c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memories",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("embedding_provider", sa.String(length=32), nullable=False),
        sa.Column("source_conversation_id", sa.UUID(), nullable=True),
        sa.Column("recall_count", sa.Integer(), nullable=False),
        sa.Column("last_recalled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('preference', 'fact', 'routine', 'relationship', 'project', 'event')",
            name=op.f("ck_memories_category_known"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_memories_confidence_in_range")
        ),
        sa.CheckConstraint(
            "importance >= 0 AND importance <= 1", name=op.f("ck_memories_importance_in_range")
        ),
        sa.CheckConstraint("length(content) > 0", name=op.f("ck_memories_content_not_empty")),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversations.id"],
            name=op.f("fk_memories_source_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(op.f("ix_memories_user_id"), "memories", ["user_id"], unique=False)
    op.create_index(
        "ix_memories_user_id_category", "memories", ["user_id", "category"], unique=False
    )
    op.create_index(
        "ix_memories_user_id_importance", "memories", ["user_id", "importance"], unique=False
    )
    # ### end Alembic commands ###

    # Approximate nearest-neighbour index over cosine distance.
    #
    # A caveat worth stating: every NOVA search also filters by user_id, and
    # HNSW applies that filter *after* traversing the graph, so at small
    # per-user counts the planner will often prefer -- and should prefer --
    # an exact scan, which is both faster and perfectly recalled. This index
    # earns its place once a single account holds tens of thousands of
    # memories. It is created now so that transition needs no migration.
    op.execute(
        "CREATE INDEX ix_memories_embedding_cosine ON memories "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_memories_embedding_cosine")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memories_user_id_importance", table_name="memories")
    op.drop_index("ix_memories_user_id_category", table_name="memories")
    op.drop_index(op.f("ix_memories_user_id"), table_name="memories")
    op.drop_table("memories")
    # ### end Alembic commands ###
